[tool.poetry]
name = "parser"
version = "0.1.0"
description = ""
authors = ["emurze <rozanov7475@yandex.by>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
selenium = "4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
