# Generated by Django 4.2.7 on 2023-11-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='href',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='src',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
