# Generated by Django 4.2.7 on 2023-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_article_image_article_href_article_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='href',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='src',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['href'], name='panel_artic_href_ff6ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['src'], name='panel_artic_src_029cf9_idx'),
        ),
    ]
