# Generated by Django 4.2.7 on 2023-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='woman/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['-created'], name='panel_woman_created_6545ce_idx')],
            },
        ),
    ]
