# Generated by Django 4.2.7 on 2023-11-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_woman_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='url',
            field=models.CharField(max_length=1012, null=True),
        ),
        migrations.AlterField(
            model_name='woman',
            name='photo',
            field=models.ImageField(upload_to='woman/%Y/%m/%d'),
        ),
    ]
