# Generated by Django 4.2.7 on 2023-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_woman_url_alter_woman_photo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='woman',
            index=models.Index(condition=models.Q(('url__isnull', False)), fields=['url'], name='woman_url_is_not_null_index'),
        ),
    ]
